// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwayh1MQyrt9JEIA8pzl-ndWCIec43RRk',
    appId: '1:217707436148:web:a886239e54194522a2d921',
    messagingSenderId: '217707436148',
    projectId: 'jetride-bc5ae',
    authDomain: 'jetride-bc5ae.firebaseapp.com',
    storageBucket: 'jetride-bc5ae.firebasestorage.app',
    measurementId: 'G-LPLXE34WK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRHNuDC6dDCqs2Io0fbNZ4RLvWcTWw_g',
    appId: '1:217707436148:android:9a28715e4a1ab693a2d921',
    messagingSenderId: '217707436148',
    projectId: 'jetride-bc5ae',
    storageBucket: 'jetride-bc5ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iew1yYV3TsRJJNKAorSRTjyjUwHqIyg',
    appId: '1:217707436148:ios:ab33fcbd3ffa56cfa2d921',
    messagingSenderId: '217707436148',
    projectId: 'jetride-bc5ae',
    storageBucket: 'jetride-bc5ae.firebasestorage.app',
    iosClientId: '217707436148-tjlgdd8don50fcjkhsk6io7nasru801h.apps.googleusercontent.com',
    iosBundleId: 'com.jetride.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iew1yYV3TsRJJNKAorSRTjyjUwHqIyg',
    appId: '1:217707436148:ios:284ccd716ae6b564a2d921',
    messagingSenderId: '217707436148',
    projectId: 'jetride-bc5ae',
    storageBucket: 'jetride-bc5ae.firebasestorage.app',
    iosClientId: '217707436148-9fk3n5nv321g0okt0quipn2ci4287q2u.apps.googleusercontent.com',
    iosBundleId: 'com.jet.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwayh1MQyrt9JEIA8pzl-ndWCIec43RRk',
    appId: '1:217707436148:web:c4f10928df744007a2d921',
    messagingSenderId: '217707436148',
    projectId: 'jetride-bc5ae',
    authDomain: 'jetride-bc5ae.firebaseapp.com',
    storageBucket: 'jetride-bc5ae.firebasestorage.app',
    measurementId: 'G-31SDXKD1WN',
  );
}
